ruby:
  enabled: false

haml:
  enabled: false

go:
  enabled: false

scss:
  config_file: .scss-style.yml
  exclude:
    - "media/css/bootstrap.min.css"
    - "media/css/daterangepicker.css"

fail_on_violations: true
